### ISSUE TITLE
Not support redis sentinels

### ISSUE THREAD

**Issue by kenticny** [koajs/koa-redis#26]
I found the `node-redis` not support sentinels, is there any solution for redis sentinels?

**Comment by DaAwesomeP** [comment]
The Redis library that we use here does not support it at this time: https://github.com/NodeRedis/node_redis/issues/302. I would not be willing to switch libraries since it is currently very stable. A wrapper or intermediate library only used when sentinels are needed would possible to implement safely. I would also like to keep test coverage at 100% though, and I'm not sure if Travis could set up a sentinel.

**Comment by Benew** [comment]
+1

**Comment by niftylettuce** [comment]
I've just released v4.0.0 which has support for Sentinels.  Please see updated docs and examples at <https://github.com/koajs/koa-redis#koa-redis>
