### ISSUE TITLE
koa-generic-session is deprecated

### ISSUE THREAD

**Issue by pho3nixf1re** [koajs/koa-redis#35]
Would there be any interest in a PR that implements support for `koa-session`? It would require a big major version bump since it would be breaking. Potentially there could be support for both using a flag or arg detection maybe. I would be willing to do the work on this but only if it is likely to be merged. It also needs more discussion.

**Comment by DaAwesomeP** [comment]
I don't see why not! It sounds like it would be a method that inputs the `options` object and returns an object for `options.store`.

cc @dead-horse

**Comment by dead-horse** [comment]
LGTM

**Comment by minchaozhang** [comment]
use devDependencies with koa-generic-session in package.json .
I use typescript make error.
![image](https://user-images.githubusercontent.com/38648223/41603062-cb52d702-740e-11e8-87a5-1816c5a43a38.png)

**Comment by niftylettuce** [comment]
I am closing this because `koa-session` does not function similarly to `express-session`, whereas `res.end` will cause a session save.  For example, you have `req.flash('error', 'Uh oh, woops!')` and then immediately after you have `res.redirect('/foo-bar')` or `res.redirect('back')` (in Koa it is `ctx.flash('error', 'Uh oh woops!')` and `ctx.redirect('back')`.  In any case, `koa-generic-session` is the _only_ session package for Koa that has support for this and exposes a `saveSession` method for use with packages like `koa-redirect-loop` (which prevents endless redirect loops in your application since HTTP Referrer header is unreliable).

Also, `koa-generic-session` is not deprecated.

Ref:
* https://github.com/koajs/generic-session/commit/5205899c49ba94d2563f2654e25f0eab6e7eb5be
* https://github.com/niftylettuce/koa-redirect-loop/blob/master/index.js#L52
* https://lad.js.org

**Comment by jgodson** [comment]
> Also, koa-generic-session is not deprecated.

@niftylettuce I think the assumption was made due to this in `koa-generic-session`'s readme:

> Notice: koa-session support external store now, please migrate to koa-session.

I'm glad to hear that it's not deprecated though!

**Comment by niftylettuce** [comment]
@jgodson 	fixed it in readme

**Comment by frangio** [comment]
This issue is the second Google result when searching "koa-generic-session", and the title shown says "koa-generic-session is deprecated". I'd suggest changing the title of the issue to a question so that people don't get the wrong impression from the search results.

**Comment by niftylettuce** [comment]
nice find, thank you @frangio 	as always 🙇
