### ISSUE TITLE
Remove hiredis dependency

### ISSUE THREAD

**Issue by gugadev** [koajs/koa-redis#38]
For windows developers, deal with hiredis is a sick, insane, and stormy nightmare. Is literally impossible compile hiredis on Windows, there are some missing dependencies with this OS.

**Comment by DaAwesomeP** [comment]
Hiredis is included as an optional dependency so that it is allowed to fail to build. It may make the install process longer, but it allows for greater performance for Linux users that can compile it. Koa redis should have still installed properly and should function regardless of it hiredis installs successfully. Please see #17.
